[package]
name = "doc-test"
version = "0.1.0"
authors = ["Bhargav Voleti <bhargav.voleti93@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
futures-preview = "0.3.0-alpha"
tokio = "0.2.0-alpha"
bytes = "0.4"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
